project:
  output-dir: docs

toc: true
number-sections: true

format:
  html:
    message: false
    warning: false
    code-fold: true
    code-overflow: scroll
    code-summary: 'Show the code'
    self-contained: true
    toc: true
    fig-align: center
    theme: cerulean
    include-in-header:
    - text: |
          <style>
          .panel-tabset > .nav-tabs,
          .panel-tabset > .tab-content {border: none;}
          </style>
